apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployubuntu
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
     metadata:
       labels:
         app: ubuntu
     spec:
       containers:
       - name: ubuntu
         image: ubuntu:18.04
         ports:
         - containerPort : 22
         resources:
           requests:
             cpu: 0.5
             memory: "5Mi"

